rules:
  - id: misconfigured-Hook
    message: $CONTRACT |&| $SIG |&| $IMPL |;|
    languages:
      - solidity
    severity: WARNING
    pattern-either:
      - patterns:
          - pattern-regex: |-
              (?P<SIG>\w+):\s*true
          - pattern-inside: |
              return Hooks.Permissions( ... );
          - pattern-inside: |
              function getHookPermissions() override returns (Hooks.Permissions) { ... }
          - pattern-inside: |
              contract $CONTRACT is ..., BaseHook, ... { ... }
      - patterns:
          - pattern-inside: |
              contract $CONTRACT { ... ... ... }
          - pattern-regex: |-
              ^\s*function\s+(?P<IMPL>\w+\s*\([\S\s,]*?\))\s*(?P<VIS>public|external|internal|private)?(?:\s+(?P<PAY>payable))?(?:\s+(?P<PURITY>view|pure))?(?:\s+(?P<OVER>override))?(?:(?P<MOD>[\S\s]*?))(?=\s+returns\b|\s*\{)(?:\s*(?P<RETURN>returns\s*\([\s\S]*?\)))?
